[build-system]
requires = ["setuptools>=61"]
build-backend = "setuptools.build_meta"

[project]
name = "azure-gating"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = "==3.11.*"
dependencies = [
    "azure-ai-ml>=1.31.0",
    "azure-identity>=1.25.1",
    "azureml-mlflow>=1.60.0",
    "black>=25.12.0",
    "lightning>=2.6.5",
    "torch",
    "mlflow<2.8.0",
    "optuna>=4.6.0",
    "optuna-integration>=4.6.0",
    "pandas>=2.3.3",
    "rich>=15.0.0",
    "scikit-learn>=1.8.0",
    "scipy>=1.16.3",
]

[tool.pyright]
executionEnvironments = [{ root = "src" }]
typeCheckingMode = "standard"
venv = ".venv"
venvPath = "."
diagnosticMode = "openFilesOnly"

[[tool.uv.index]]
name = "pytorch-cu124"
url = "https://download.pytorch.org/whl/cu124"
explicit = true

[tool.uv.sources]
torch = { index = "pytorch-cu124" }

# This is old from another project with incorrect format. 
# [tool.setuptools.packages.find]
# where = ["src"]
